# Generated by Django 4.2.4 on 2023-10-10 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('block_users', 'can blocking users'),)},
        ),
    ]
