# Generated by Django 4.2.4 on 2023-10-09 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.EmailField(max_length=254, unique=True, verbose_name='Почтовый адрес')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('comment', models.TextField(verbose_name='Краткий комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='MailingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Время начала рассылки')),
                ('mailing_period', models.CharField(choices=[('day', 'раз в день'), ('week', 'раз в неделю'), ('month', 'раз в месяц')], default='day', max_length=6, verbose_name='Периодичность рассылки')),
                ('mailing_stop_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания рассылки')),
                ('mailing_state', models.CharField(choices=[('F', 'завершена'), ('R', 'запущена'), ('C', 'создана')], default='C', max_length=1, verbose_name='Статус')),
                ('clients', models.ManyToManyField(to='skychimp.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Настройка рассылки',
                'verbose_name_plural': 'Настройки рассылки',
            },
        ),
        migrations.CreateModel(
            name='UserMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Тема письма')),
                ('body', models.TextField(verbose_name='Тема письма')),
            ],
            options={
                'verbose_name': 'Сообщение для рассылки',
                'verbose_name_plural': 'Сообщения для рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingTry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('try_time', models.DateTimeField(verbose_name='Дата попытки')),
                ('try_state', models.BooleanField(blank=True, null=True, verbose_name='Статус попытки')),
                ('server_response', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ответ сервера')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skychimp.mailingconfig', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылки',
            },
        ),
        migrations.AddField(
            model_name='mailingconfig',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='skychimp.usermail', verbose_name='Сообщение'),
        ),
    ]
