# Generated by Django 4.2.4 on 2023-10-10 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skychimp', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingconfig',
            options={'permissions': (('stop_mailing', 'can stop mailing'),), 'verbose_name': 'Настройка рассылки', 'verbose_name_plural': 'Настройки рассылки'},
        ),
    ]
